const SET_SEARCH_TEXT = 'companies/SET_SEARCH_TEXT';
const SET_ORDERING_KEY = 'companies/SET_ORDERING_KEY';
const SET_ORDERING_DIRECTION = 'companies/SET_ORDERING_DIRECTION';
const FILTER_COMPANIES = 'companies/FILTER_COMPANIES';

const REQUEST_DATA_OVERVIEW = 'companies/REQUEST_DATA_OVERVIEW';
const REQUEST_DELETE_DATA = 'companies/REQUEST_DELETE_DATA';
const REQUEST_REMOVE_CONSENT = 'companies/REQUEST_REMOVE_CONSENT';
const REQUEST_UPDATE = 'companies/REQUEST_UPDATE';

export default {
  SET_SEARCH_TEXT,
  SET_ORDERING_KEY,
  SET_ORDERING_DIRECTION,
  FILTER_COMPANIES,
  REQUEST_DATA_OVERVIEW,
  REQUEST_DELETE_DATA,
  REQUEST_REMOVE_CONSENT,
  REQUEST_UPDATE,
};
