const GIVE_CONSENT = 'consent/GIVE_CONSENT';
const VALIDATE_GIVE_CONSENT = 'consent/VALIDATE_GIVE_CONSENT';
const REMOVE_CONSENT = 'consent/REMOVE_CONSENT';
const VALIDATE_REMOVE_CONSENT = 'consent/VALIDATE_REMOVE_CONSENT';
const CLEAR_VALIDATING = 'consent/CLEAR_VALIDATING';

export default {
  GIVE_CONSENT,
  VALIDATE_GIVE_CONSENT,
  REMOVE_CONSENT,
  VALIDATE_REMOVE_CONSENT,
  CLEAR_VALIDATING,
};
