const CLEAR_VALIDATING = 'consent/CLEAR_VALIDATING';
const VALIDATE_CONSENT = 'consent/VALIDATE_CONSENT';

const FETCH_LIST_REQUEST = 'consent/FETCH_LIST_REQUEST';
const FETCH_LIST_FAILED = 'consent/FETCH_LIST_FAILED';
const FETCH_LIST_COMPLETE = 'consent/FETCH_LIST_COMPLETE';

const CONSENT_UPDATED = 'consent/CONSENT_UPDATED';

export default {
  VALIDATE_CONSENT,
  CLEAR_VALIDATING,
  CONSENT_UPDATED,
  FETCH_LIST_REQUEST,
  FETCH_LIST_FAILED,
  FETCH_LIST_COMPLETE,
};
