const TOGGLE_MENU = 'ui/TOGGLE_MENU';

const DISPLAY_CONSENT_DIALOG = 'ui/DISPLAY_CONSENT_DIALOG';
const HIDE_CONSENT_DIALOG = 'ui/HIDE_CONSENT_DIALOG';

const DISPLAY_PRIVACY_POLICY_DIALOG = 'ui/DISPLAY_PRIVACY_POLICY_DIALOG';
const HIDE_PRIVACY_POLICY_DIALOG = 'ui/HIDE_PRIVACY_POLICY_DIALOG';

const SET_TOKEN = 'ui/SET_TOKEN';
const REMOVE_TOKEN = 'ui/REMOVE_TOKEN';

export default {
  TOGGLE_MENU,
  DISPLAY_CONSENT_DIALOG,
  HIDE_CONSENT_DIALOG,
  DISPLAY_PRIVACY_POLICY_DIALOG,
  HIDE_PRIVACY_POLICY_DIALOG,
  SET_TOKEN,
  REMOVE_TOKEN,
};
