const TOGGLE_MENU = 'ui/TOGGLE_MENU';

const DISPLAY_CONSENT_DIALOG = 'ui/DISPLAY_CONSENT_DIALOG';
const HIDE_CONSENT_DIALOG = 'ui/HIDE_CONSENT_DIALOG';

export default {
  TOGGLE_MENU,
  DISPLAY_CONSENT_DIALOG,
  HIDE_CONSENT_DIALOG,
};
