const SET_SEARCH_TEXT = 'requests/SET_SEARCH_TEXT';
const SET_ORDERING_KEY = 'requests/SET_ORDERING_KEY';
const SET_ORDERING_DIRECTION = 'requests/SET_ORDERING_DIRECTION';
const FILTER_REQUESTS = 'requests/FILTER_REQUESTS';

const CREATE_REQUEST_COMPLETE = 'requests/CREATE_REQUEST_COMPLETE';

export default {
  SET_SEARCH_TEXT,
  SET_ORDERING_KEY,
  SET_ORDERING_DIRECTION,
  FILTER_REQUESTS,
  CREATE_REQUEST_COMPLETE,
};
